"""Expand employee model and add address document bank statutory tables

Revision ID: 85dd719ca07a
Revises: cf8f4f5b73f2
Create Date: 2026-07-01 13:52:47.943719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '85dd719ca07a'
down_revision: Union[str, None] = 'cf8f4f5b73f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=False, comment='current | permanent'),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_bank_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=150), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('ifsc_code', sa.String(length=20), nullable=False),
    sa.Column('branch_name', sa.String(length=150), nullable=True),
    sa.Column('account_holder_name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False, comment='savings|current|salary'),
    sa.Column('is_primary', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False, comment='AADHAAR|PAN|PASSPORT|DL|VOTER_ID|OTHER'),
    sa.Column('document_label', sa.String(length=150), nullable=True, comment='Custom label for OTHER type'),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('issuing_authority', sa.String(length=200), nullable=True),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('drive_file_id', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_statutory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('uan_number', sa.String(length=20), nullable=True),
    sa.Column('pf_member_id', sa.String(length=50), nullable=True),
    sa.Column('pf_eligible', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('pf_joining_date', sa.Date(), nullable=True),
    sa.Column('vpf_eligible', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('eps_eligible', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('edli_eligible', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('esic_ip_number', sa.String(length=20), nullable=True),
    sa.Column('esic_eligible', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('esic_joining_date', sa.Date(), nullable=True),
    sa.Column('esic_dispensary', sa.String(length=200), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('pt_state', sa.String(length=100), nullable=True, comment='State for Professional Tax slab'),
    sa.Column('aadhaar_linked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('pan_linked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('bank_verified', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('uan_activated', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('kyc_verified', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('esic_ip_number'),
    sa.UniqueConstraint('uan_number')
    )
    op.add_column('employees', sa.Column('biometric_code', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('display_name', sa.String(length=200), nullable=True))
    op.add_column('employees', sa.Column('blood_group', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', 'UNKNOWN', name='bloodgroup'), nullable=True))
    op.add_column('employees', sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'OTHER', name='maritalstatus'), nullable=True))
    op.add_column('employees', sa.Column('nationality', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('religion', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('personal_email', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('company_email', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('alternate_mobile', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('confirmation_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('resignation_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('relieving_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('employment_type', sa.Enum('PERMANENT', 'PROBATION', 'CONTRACT', 'INTERN', 'PART_TIME', 'CONSULTANT', name='employmenttype'), nullable=True))
    op.add_column('employees', sa.Column('employee_status', sa.Enum('ACTIVE', 'PROBATION', 'NOTICE_PERIOD', 'INACTIVE', 'TERMINATED', name='employeestatus'), nullable=False))
    op.add_column('employees', sa.Column('reporting_manager_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('branch', sa.String(length=150), nullable=True))
    op.add_column('employees', sa.Column('location', sa.String(length=150), nullable=True))
    op.add_column('employees', sa.Column('grade', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('shift', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('cost_center', sa.String(length=100), nullable=True))
    op.drop_index('ix_employees_email', table_name='employees')
    op.create_index(op.f('ix_employees_company_email'), 'employees', ['company_email'], unique=True)
    op.create_unique_constraint(None, 'employees', ['biometric_code'])
    op.create_foreign_key(None, 'employees', 'employees', ['reporting_manager_id'], ['id'])
    op.drop_column('employees', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_index(op.f('ix_employees_company_email'), table_name='employees')
    op.create_index('ix_employees_email', 'employees', ['email'], unique=True)
    op.drop_column('employees', 'cost_center')
    op.drop_column('employees', 'shift')
    op.drop_column('employees', 'grade')
    op.drop_column('employees', 'location')
    op.drop_column('employees', 'branch')
    op.drop_column('employees', 'reporting_manager_id')
    op.drop_column('employees', 'employee_status')
    op.drop_column('employees', 'employment_type')
    op.drop_column('employees', 'relieving_date')
    op.drop_column('employees', 'resignation_date')
    op.drop_column('employees', 'confirmation_date')
    op.drop_column('employees', 'alternate_mobile')
    op.drop_column('employees', 'mobile_number')
    op.drop_column('employees', 'company_email')
    op.drop_column('employees', 'personal_email')
    op.drop_column('employees', 'religion')
    op.drop_column('employees', 'nationality')
    op.drop_column('employees', 'marital_status')
    op.drop_column('employees', 'blood_group')
    op.drop_column('employees', 'display_name')
    op.drop_column('employees', 'middle_name')
    op.drop_column('employees', 'biometric_code')
    op.drop_table('employee_statutory')
    op.drop_table('employee_documents')
    op.drop_table('employee_bank_accounts')
    op.drop_table('employee_addresses')
    # ### end Alembic commands ###
