import { useEffect, useState } from "react";
import {
  listDepartments,
  listDesignations,
  listEmployeesDropdown,
  createDepartment,
  createDesignation,
} from "../../../services/employeeService";

const inputCls = "w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500";

function Field({ label, children, hint }) {
  return (
    <div>
      <label className="block text-sm font-medium text-gray-700 mb-1">{label}</label>
      {children}
      {hint && <p className="text-xs text-gray-400 mt-1">{hint}</p>}
    </div>
  );
}

function InlineAdd({ placeholder, onAdd }) {
  const [value, setValue] = useState("");
  const [loading, setLoading] = useState(false);

  async function handle() {
    if (!value.trim()) return;
    setLoading(true);
    try { await onAdd(value.trim()); setValue(""); }
    finally { setLoading(false); }
  }

  return (
    <div className="flex gap-2 mt-1">
      <input
        type="text"
        value={value}
        onChange={(e) => setValue(e.target.value)}
        onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), handle())}
        placeholder={placeholder}
        className="flex-1 border border-gray-200 rounded px-2 py-1 text-xs focus:outline-none focus:ring-1 focus:ring-indigo-400"
      />
      <button
        type="button"
        onClick={handle}
        disabled={loading || !value.trim()}
        className="text-xs text-indigo-600 hover:underline disabled:opacity-40 whitespace-nowrap"
      >
        + Add
      </button>
    </div>
  );
}

export default function StepEmployment({ data, onChange, employeeCode }) {
  const [departments, setDepartments] = useState([]);
  const [designations, setDesignations] = useState([]);
  const [managers, setManagers] = useState([]);

  useEffect(() => {
    Promise.all([listDepartments(), listDesignations(), listEmployeesDropdown()]).then(
      ([d, des, m]) => { setDepartments(d); setDesignations(des); setManagers(m); }
    );
  }, []);

  const set = (field) => (e) => onChange({ ...data, [field]: e.target.value || null });
  const setNum = (field) => (e) => onChange({ ...data, [field]: e.target.value ? Number(e.target.value) : null });

  async function handleAddDept(name) {
    const dept = await createDepartment(name);
    setDepartments((prev) => [...prev, dept]);
    onChange({ ...data, department_id: dept.id });
  }

  async function handleAddDesig(title) {
    const desig = await createDesignation(title);
    setDesignations((prev) => [...prev, desig]);
    onChange({ ...data, designation_id: desig.id });
  }

  return (
    <div className="space-y-6">
      {/* Employee code (read-only) */}
      <Field label="Employee Code" hint="Auto-generated by the system">
        <input
          className={`${inputCls} bg-gray-50 text-gray-500 cursor-not-allowed`}
          value={employeeCode || "Will be assigned on save"}
          readOnly
        />
      </Field>

      <div className="grid grid-cols-2 gap-4">
        <Field label="Biometric Code">
          <input
            className={inputCls}
            value={data.biometric_code ?? ""}
            onChange={set("biometric_code")}
            placeholder="Biometric / attendance device ID"
          />
        </Field>
        <Field label="Employment Type">
          <select className={inputCls} value={data.employment_type ?? ""} onChange={set("employment_type")}>
            <option value="">— Select —</option>
            <option value="permanent">Permanent</option>
            <option value="probation">Probationary</option>
            <option value="contract">Contract</option>
            <option value="intern">Intern / Trainee</option>
            <option value="part_time">Part-Time</option>
            <option value="consultant">Consultant</option>
          </select>
        </Field>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <Field label="Employee Status">
          <select className={inputCls} value={data.employee_status ?? "active"} onChange={set("employee_status")}>
            <option value="active">Active</option>
            <option value="probation">On Probation</option>
            <option value="notice_period">Serving Notice Period</option>
            <option value="inactive">Inactive</option>
            <option value="terminated">Terminated</option>
          </select>
        </Field>
        <Field label="Grade">
          <input
            className={inputCls}
            value={data.grade ?? ""}
            onChange={set("grade")}
            placeholder="e.g. G3, Senior"
          />
        </Field>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <Field label="Date of Joining">
          <input type="date" className={inputCls} value={data.date_of_joining ?? ""} onChange={set("date_of_joining")} />
        </Field>
        <Field label="Confirmation Date">
          <input type="date" className={inputCls} value={data.confirmation_date ?? ""} onChange={set("confirmation_date")} />
        </Field>
      </div>

      {/* Department */}
      <div className="grid grid-cols-2 gap-4">
        <Field label="Department">
          <select
            className={inputCls}
            value={data.department_id ?? ""}
            onChange={setNum("department_id")}
          >
            <option value="">— None —</option>
            {departments.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}
          </select>
          <InlineAdd placeholder="New department…" onAdd={handleAddDept} />
        </Field>

        <Field label="Designation">
          <select
            className={inputCls}
            value={data.designation_id ?? ""}
            onChange={setNum("designation_id")}
          >
            <option value="">— None —</option>
            {designations.map((d) => <option key={d.id} value={d.id}>{d.title}</option>)}
          </select>
          <InlineAdd placeholder="New designation…" onAdd={handleAddDesig} />
        </Field>
      </div>

      {/* Reporting Manager */}
      <Field label="Reporting Manager">
        <select
          className={inputCls}
          value={data.reporting_manager_id ?? ""}
          onChange={setNum("reporting_manager_id")}
        >
          <option value="">— None —</option>
          {managers.map((m) => (
            <option key={m.id} value={m.id}>
              {m.first_name} {m.last_name} ({m.employee_code})
            </option>
          ))}
        </select>
      </Field>

      <div className="grid grid-cols-3 gap-4">
        <Field label="Branch">
          <input className={inputCls} value={data.branch ?? ""} onChange={set("branch")} placeholder="e.g. Mumbai HO" />
        </Field>
        <Field label="Location">
          <input className={inputCls} value={data.location ?? ""} onChange={set("location")} placeholder="e.g. 4th Floor" />
        </Field>
        <Field label="Shift">
          <input className={inputCls} value={data.shift ?? ""} onChange={set("shift")} placeholder="e.g. General Shift" />
        </Field>
      </div>

      <Field label="Cost Center">
        <input className={inputCls} value={data.cost_center ?? ""} onChange={set("cost_center")} placeholder="e.g. CC-HR-001" />
      </Field>
    </div>
  );
}
